[package]
name = "oasis-core-runtime-loader"
version = "0.3.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
edition = "2018"

[dependencies]
aesm-client = { version = "0.2.0", features = ["sgxs"] }
enclave-runner = "0.2.0"
sgxs-loaders = "0.2.0"
clap = "2.29.1"
failure = "0.1.5"

[[bin]]
name = "oasis-core-runtime-loader"
path ="bin/main.rs"
