[package]
name = "oasis-core-runtime-loader"
version = "0.0.0"
authors = ["Oasis Protocol Foundation <info@oasisprotocol.org>"]
edition = "2018"

[dependencies]
clap = "2.29.1"
failure = "0.1.5"
futures = { version = "0.3.17", features = ["compat", "io-compat"] }
# NOTE: The version of tokio is constrained by what the upstream enclave-runner is using.
tokio = { version = "1.11", features = ["full"] }

[target.'cfg(target_os = "linux")'.dependencies]
aesm-client = { version = "0.5.3", features = ["sgxs"] }
enclave-runner = "0.4.0"
sgxs-loaders = "0.3.1"

[[bin]]
name = "oasis-core-runtime-loader"
path ="bin/main.rs"
