[package]
name = "oasis-core-runtime-loader"
version = "0.0.0"
authors = ["Oasis Protocol Foundation <info@oasisprotocol.org>"]
edition = "2018"

[dependencies]
clap = "3.2.10"
failure = "0.1.5"
futures = { version = "0.3.17", features = ["compat", "io-compat"] }
# NOTE: The version of tokio is constrained by what the upstream enclave-runner is using.
tokio = { version = "1.20", features = ["full"] }

[target.'cfg(target_os = "linux")'.dependencies]
aesm-client = { git = "https://github.com/fortanix/rust-sgx", rev = "998c34d158a69dd1af33f22587e8ae1c26ca6a27", features = ["sgxs"] }
enclave-runner = { git = "https://github.com/fortanix/rust-sgx", rev = "998c34d158a69dd1af33f22587e8ae1c26ca6a27" }
sgxs-loaders = { git = "https://github.com/fortanix/rust-sgx", rev = "998c34d158a69dd1af33f22587e8ae1c26ca6a27" }

[[bin]]
name = "oasis-core-runtime-loader"
path = "bin/main.rs"
