[package]
name = "ekiden-node-dummy"
version = "0.2.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden dummy node"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"

[dependencies]
ekiden-beacon-api = { path = "../../beacon/api", version = "0.2.0-alpha" }
ekiden-beacon-base = { path = "../../beacon/base", version = "0.2.0-alpha" }
ekiden-beacon-dummy = { path = "../../beacon/dummy", version = "0.2.0-alpha" }
ekiden-core = { path = "../../core/common", version = "0.2.0-alpha" }
ekiden-consensus-api = { path = "../../consensus/api", version = "0.2.0-alpha" }
ekiden-consensus-base = { path = "../../consensus/base", version = "0.2.0-alpha" }
ekiden-consensus-dummy = { path = "../../consensus/dummy", version = "0.2.0-alpha" }
ekiden-common-api = { path = "../../common/api", version = "0.2.0-alpha" }
ekiden-common = { path = "../../common", version = "0.2.0-alpha" }
ekiden-node-dummy-api = { path = "./api", version = "0.2.0-alpha" }
ekiden-registry-api = { path = "../../registry/api", version = "0.2.0-alpha" }
ekiden-registry-base = { path = "../../registry/base", version = "0.2.0-alpha" }
ekiden-registry-dummy = { path = "../../registry/dummy", version = "0.2.0-alpha" }
ekiden-scheduler-api = { path = "../../scheduler/api", version = "0.2.0-alpha" }
ekiden-scheduler-base = { path = "../../scheduler/base", version = "0.2.0-alpha" }
ekiden-scheduler-dummy = { path = "../../scheduler/dummy", version = "0.2.0-alpha" }
ekiden-storage-api = { path = "../../storage/api", version = "0.2.0-alpha" }
ekiden-storage-base = { path = "../../storage/base", version = "0.2.0-alpha" }
ekiden-storage-dummy = { path = "../../storage/dummy", version = "0.2.0-alpha" }
clap = "2.29.1"
grpcio = "0.2.2"
log = "0.4"
pretty_env_logger = "0.2"
futures-timer = "0.1.1"
ansi_term = "0.11"

[[bin]]
name = "ekiden-node-dummy"
path = "src/main.rs"

[[bin]]
name = "ekiden-node-dummy-controller"
path = "src/bin/controller.rs"
