[package]
name = "token-api"
version = "0.2.0-alpha"
authors = [
    "Raymond Cheng <me@raymondcheng.net>",
    "Jernej Kos <jernej@kos.mx>"
]
build = "build.rs"

[dependencies]
ekiden-core = { path = "../../../core/common" }
protobuf = "~2.0"
serde = "=1.0.59"

[build-dependencies]
ekiden-tools = { path = "../../../tools" }
