[package]
name = "ekiden-edl"
version = "0.2.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden EDL"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"

[dependencies]
ekiden-tools = { path = "../../tools", version = "0.2.0-alpha" }
ekiden-enclave-edl = { path = "../../enclave/edl", version = "0.2.0-alpha" }
ekiden-rpc-edl = { path = "../../rpc/edl", version = "0.2.0-alpha" }
ekiden-db-edl = { path = "../../db/edl", version = "0.2.0-alpha" }
ekiden-contract-edl = { path = "../../contract/edl", version = "0.2.0-alpha" }
sgx_edl = { git = "https://github.com/ekiden/rust-sgx-sdk", tag = "v0.9.8-ekiden1" }
