[package]
name = "ekiden-db-trusted"
version = "0.1.0-alpha.3"
authors = ["Ekiden Developers <ekiden-dev@googlegroups.com>"]
description = "Ekiden database (trusted part)"
keywords = ["ekiden"]
repository = "https://github.com/ekiden/ekiden"

[dependencies]
bsdiff = "0.1.3"
bzip2 = "0.3.2"
ekiden-common = { path = "../../common", version = "0.1.0-alpha.3" }
ekiden-enclave-trusted = { path = "../../enclave/trusted", version = "0.1.0-alpha.3" }
ekiden-key-manager-client = { path = "../../contracts/key-manager/client", version = "0.1.0-alpha.3" }
lazy_static = { version = "1.0", features = ["spin_no_std"] }
protobuf = "1.4.3"
sodalite = "0.3.0"
serde = "1.0"
serde_cbor = "0.8.2"

[build-dependencies]
ekiden-tools = { path = "../../tools", version = "0.1.0-alpha.3" }
