[package]
name = "ekiden-db-trusted"
version = "0.2.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden database (trusted part)"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"

[dependencies]
ekiden-common = { path = "../../common", version = "0.2.0-alpha" }
ekiden-enclave-common = { path = "../../enclave/common", version = "0.2.0-alpha" }
ekiden-enclave-trusted = { path = "../../enclave/trusted", version = "0.2.0-alpha" }
ekiden-storage-base = { path = "../../storage/base", version = "0.2.0-alpha" }
ekiden-storage-lru = { path = "../../storage/lru_cache", version = "0.2.0-alpha" }
ekiden-keymanager-client = { path = "../../key-manager/client", version = "0.2.0-alpha" }
ekiden-keymanager-common = { path = "../../key-manager/common", version = "0.2.0-alpha" }
lazy_static = { version = "1.1.0", features = ["spin_no_std"] }
protobuf = "~2.0"
sodalite = "0.3.0"
serde = "1.0.71"
serde_derive = "1.0"
bincode = "1.0.0"

[target.'cfg(not(target_env = "sgx"))'.dependencies]
ekiden-storage-dummy = { path = "../../storage/dummy", version = "0.2.0-alpha" }

[build-dependencies]
ekiden-tools = { path = "../../tools", version = "0.2.0-alpha" }
