[package]
name = "ekiden-db-trusted"
version = "0.1.0-alpha.4"
authors = ["Ekiden Developers <ekiden-dev@googlegroups.com>"]
description = "Ekiden database (trusted part)"
keywords = ["ekiden"]
repository = "https://github.com/ekiden/ekiden"

[dependencies]
ekiden-common = { path = "../../common", version = "0.1.0-alpha.4" }
ekiden-enclave-trusted = { path = "../../enclave/trusted", version = "0.1.0-alpha.4" }
ekiden-key-manager-client = { path = "../../contracts/key-manager/client", version = "0.1.0-alpha.4" }
ekiden-storage-base = { path = "../../storage/base", version = "0.1.0-alpha.4" }
lazy_static = { version = "1.0", features = ["spin_no_std"] }
protobuf = "~1.4"
sodalite = "0.3.0"
serde = "1.0"
serde_cbor = "0.8.2"
serde_derive = "1.0"

[build-dependencies]
ekiden-tools = { path = "../../tools", version = "0.1.0-alpha.4" }
