[package]
name = "ekiden-storage-dummy"
version = "0.1.0-alpha.4"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden storage interface traits"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"

[dependencies]
ekiden-common = { path = "../../common", version = "0.1.0-alpha.4" }
ekiden-storage-base = { path = "../base", version = "0.1.0-alpha.4" }
