[package]
name = "ekiden-consensus-dummy"
version = "0.1.0-alpha.4"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden dummy in-memory consensus backend"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"

[dependencies]
ekiden-common = { path = "../../common", version = "0.1.0-alpha.4" }
ekiden-consensus-base = { path = "../base", version = "0.1.0-alpha.4" }
log = "0.4"
