[package]
name = "ekiden-contract-trusted"
version = "0.2.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden contract interface (trusted part)"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"

[dependencies]
ekiden-common = { path = "../../common", version = "0.2.0-alpha" }
ekiden-contract-common = { path = "../common", version = "0.2.0-alpha" }
ekiden-enclave-trusted = { path = "../../enclave/trusted", version = "0.2.0-alpha" }
lazy_static = { version = "1.0", features = ["spin_no_std"] }
serde = "=1.0.59"
serde_cbor = "0.8.2"

[dev-dependencies]
serde_derive = "1.0"
