[package]
name = "ekiden-enclave-common"
version = "0.1.0-alpha.3"
authors = [
    "Raymond Cheng <me@raymondcheng.net>",
    "Jernej Kos <jernej@kos.mx>"
]
build = "build.rs"

[dependencies]
base64 = "0.9.0"
byteorder = "1.2.1"
ekiden-common = { path = "../../common", version = "0.1.0-alpha.3" }
protobuf = "1.4.3"
serde_json = { git = "https://github.com/ekiden/json" }
sodalite = "0.3.0"

[target.'cfg(not(target_env = "sgx"))'.dependencies]
rand = "0.4.2"
sgx_types = { git = "https://github.com/ekiden/rust-sgx-sdk", tag = "v0.9.7-ekiden1" }

[build-dependencies]
ekiden-tools = { path = "../../tools", version = "0.1.0-alpha.3" }
