[package]
name = "ekiden-enclave-common"
version = "0.2.0-alpha"
authors = [
    "Raymond Cheng <me@raymondcheng.net>",
    "Jernej Kos <jernej@kos.mx>"
]
build = "build.rs"

[dependencies]
base64 = "0.9.0"
byteorder = "1.2.1"
chrono = "0.4.2"
ekiden-common = { path = "../../common", version = "0.2.0-alpha" }
protobuf = "~2.0"
sodalite = "0.3.0"
pem-iterator = "0.2"
percent-encoding = "1.0.1"
webpki = { git = "https://github.com/oasislabs/webpki", branch = "0.17.0-ekiden", default-features = false }
serde = "=1.0.59"
serde_json = "1.0"

[target.'cfg(not(target_env = "sgx"))'.dependencies]
rand = "0.4.2"
sgx_types = { git = "https://github.com/oasislabs/rust-sgx-sdk", tag = "v0.9.8-ekiden1" }

[build-dependencies]
ekiden-tools = { path = "../../tools", version = "0.2.0-alpha" }
