[package]
name = "ekiden-storage-multilayer"
version = "0.2.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "A layered Ekiden storage backend implementing the untrusted portion of RFC 0004"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"

[dependencies]
clap = "2.31.2"
futures = "0.1"
log = "0.4.1"
rusoto_core = "0.32.0"
tokio-core = "0.1.17"

ekiden-common = { path = "../../common", version = "0.2.0-alpha" }
ekiden-di = { path = "../../di", version = "0.2.0-alpha" }
ekiden-epochtime = { path = "../../epochtime", version = "0.2.0-alpha" }
ekiden-storage-base = { path = "../base", version = "0.2.0-alpha" }
ekiden-storage-dynamodb = { path = "../dynamodb", version = "0.2.0-alpha" }
ekiden-storage-persistent = { path = "../persistent", version = "0.2.0-alpha" }
