[package]
name = "ekiden-contract-client"
version = "0.2.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden contract client functionality"
keywords = ["ekiden"]
repository = "https://github.com/ekiden/ekiden"

[dependencies]
ekiden-common = { path = "../../common", version = "0.2.0-alpha" }
ekiden-roothash-base = { path = "../../roothash/base", version = "0.2.0-alpha" }
ekiden-contract-common = { path = "../common", version = "0.2.0-alpha" }
ekiden-enclave-common = { path = "../../enclave/common", version = "0.2.0-alpha" }
ekiden-scheduler-base = { path = "../../scheduler/base", version = "0.2.0-alpha" }
ekiden-storage-base = { path = "../../storage/base", version = "0.2.0-alpha" }
ekiden-registry-base = { path = "../../registry/base", version = "0.2.0-alpha" }
ekiden-compute-api = { path = "../../compute/api", version = "0.2.0-alpha" }
serde = "=1.0.59"
serde_cbor = "0.8.2"
log = "0.4"
ekiden-grpcio = { version = "0.3.2", features = ["openssl"] }
