[package]
name = "ekiden-contract-client"
version = "0.2.0-alpha"
authors = ["Ekiden Developers <ekiden-dev@googlegroups.com>"]
description = "Ekiden contract client functionality"
keywords = ["ekiden"]
repository = "https://github.com/ekiden/ekiden"

[dependencies]
ekiden-common = { path = "../../common", version = "0.2.0-alpha" }
ekiden-contract-common = { path = "../common", version = "0.2.0-alpha" }
ekiden-enclave-common = { path = "../../enclave/common", version = "0.2.0-alpha" }
ekiden-rpc-client = { path = "../../rpc/client", version = "0.2.0-alpha" }
serde = "1.0"
serde_cbor = "0.8.2"
