[package]
name = "ekiden-contract-untrusted"
version = "0.2.0-alpha"
authors = ["Ekiden Developers <ekiden-dev@googlegroups.com>"]
description = "Ekiden contract interface (untrusted part)"
keywords = ["ekiden"]
repository = "https://github.com/ekiden/ekiden"

[features]
sgx-simulation = []

[dependencies]
sgx_types = { git = "https://github.com/ekiden/rust-sgx-sdk", tag = "v0.9.8-ekiden1" }
sgx_urts = { git = "https://github.com/ekiden/rust-sgx-sdk", tag = "v0.9.8-ekiden1" }
ekiden-common = { path = "../../common", version = "0.2.0-alpha" }
ekiden-contract-common = { path = "../common", version = "0.2.0-alpha" }
ekiden-enclave-untrusted = { path = "../../enclave/untrusted", version = "0.2.0-alpha" }
serde = "1.0"
serde_cbor = "0.8.2"

[build-dependencies]
ekiden-tools = { path = "../../tools", version = "0.2.0-alpha" }
