[package]
name = "ekiden-enclave-logger"
version = "0.2.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "a logger that works for both trusted and untrusted world"
keywords = ["ekiden", "logging"]
repository = "https://github.com/ekiden/ekiden"

[features]
default = []

[dependencies]
log = "0.4"