[package]
name = "ekiden-db-edl"
version = "0.1.0-alpha.1"
authors = ["Ekiden Developers <ekiden-dev@googlegroups.com>"]
description = "Ekiden database EDL"
keywords = ["ekiden"]
repository = "https://github.com/ekiden/ekiden"

[dependencies]
ekiden-tools = { path = "../../tools", version = "0.1.0-alpha.1" }
