[package]
name = "ekiden-rpc-trusted"
version = "0.2.0-alpha"
authors = ["Ekiden Developers <ekiden-dev@googlegroups.com>"]
description = "Ekiden RPC (trusted part)"
keywords = ["ekiden"]
repository = "https://github.com/ekiden/ekiden"

[dependencies]
sodalite = "0.3.0"
protobuf = "~1.4"
lazy_static = { version = "1.0", features = ["spin_no_std"] }
ekiden-common = { path = "../../common", version = "0.2.0-alpha" }
ekiden-enclave-common = { path = "../../enclave/common", version = "0.2.0-alpha" }
ekiden-enclave-trusted = { path = "../../enclave/trusted", version = "0.2.0-alpha" }
ekiden-rpc-common = { path = "../common", version = "0.2.0-alpha" }
ekiden-rpc-client = { path = "../client", version = "0.2.0-alpha" }
serde = "1.0"
serde_cbor = "0.8.2"

[target.'cfg(target_env = "sgx")'.dependencies]
futures-sgx = { git = "https://github.com/ekiden/futures-rs" }

[target.'cfg(not(target_env = "sgx"))'.dependencies]
rand = "0.4.2"
futures = "0.1"

[build-dependencies]
ekiden-tools = { path = "../../tools", version = "0.2.0-alpha" }
