[package]
name = "ekiden-storage-persistent"
version = "0.1.0-alpha.4"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden Persisted (locally) storage backend"
keywords = ["ekiden", "sled"]
repository = "https://github.com/oasislabs/ekiden"

[dependencies]
ekiden-common = { path = "../../common", version = "0.1.0-alpha.4" }
ekiden-storage-base = { path = "../base", version = "0.1.0-alpha.4" }
base64 = "~0.6.0"
serde_cbor = "0.8.2"
sled = "~0.15.0"
