[package]
name = "ekiden-scheduler-api"
version = "0.1.0-alpha.4"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden scheduler API"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"
build = "build.rs"

[dependencies]
ekiden-common-api = { path = "../../common/api", version = "0.1.0-alpha.4" }
protobuf = "1.4.2"
grpcio = "0.2.2"
futures = "0.1"

[build-dependencies]
ekiden-tools = { path = "../../tools", version = "0.1.0-alpha.4" }
protoc-grpcio = "0.1.0"
