[package]
name = "ekiden-rpc-client"
version = "0.2.0-alpha"
authors = ["Ekiden Developers <ekiden-dev@googlegroups.com>"]
description = "Ekiden RPC client"
keywords = ["ekiden"]
repository = "https://github.com/ekiden/ekiden"

[dependencies]
ekiden-common = { path = "../../common", version = "0.2.0-alpha" }
ekiden-enclave-common = { path = "../../enclave/common", version = "0.2.0-alpha" }
ekiden-rpc-common = { path = "../common", version = "0.2.0-alpha" }
protobuf = "~2.0"
sodalite = "0.3.0"
serde = "=1.0.59"
serde_cbor = "0.8.2"

[target.'cfg(target_env = "sgx")'.dependencies]
futures-sgx = { git = "https://github.com/ekiden/futures-rs" }

[target.'cfg(not(target_env = "sgx"))'.dependencies]
ekiden-compute-api = { path = "../../compute/api", version = "0.2.0-alpha" }
byteorder = "1.2.1"
futures = "0.1"
grpcio = { git = "https://github.com/ekiden/grpc-rs", tag = "v0.3.0-ekiden2", features = ["openssl"] }
rand = "0.4"
tokio-core = "0.1"
