[package]
name = "ekiden-runtime-untrusted"
version = "0.2.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden runtime interface (untrusted part)"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"

[features]
sgx-simulation = []

[dependencies]
sgx_types = { git = "https://github.com/oasislabs/rust-sgx-sdk", tag = "v1.0.1-ekiden3" }
sgx_urts = { git = "https://github.com/oasislabs/rust-sgx-sdk", tag = "v1.0.1-ekiden3" }
ekiden-common = { path = "../../common", version = "0.2.0-alpha" }
ekiden-runtime-common = { path = "../common", version = "0.2.0-alpha" }
ekiden-enclave-untrusted = { path = "../../enclave/untrusted", version = "0.2.0-alpha" }
ekiden-roothash-base = { path = "../../roothash/base", version = "0.2.0-alpha" }
serde = "1.0.71"
serde_cbor = { git = "https://github.com/oasislabs/cbor", tag = "v0.9.0-ekiden1" }

[build-dependencies]
ekiden-tools = { path = "../../tools", version = "0.2.0-alpha" }
