[package]
name = "ekiden-storage-base"
version = "0.2.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden storage interface traits"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"

[dependencies]
ekiden-common = { path = "../../common", version = "0.2.0-alpha" }

[target.'cfg(not(target_env = "sgx"))'.dependencies]
ekiden-storage-api = { path = "../api", version = "0.2.0-alpha" }
grpcio = { git = "https://github.com/ekiden/grpc-rs", tag = "v0.3.0-ekiden2", features = ["openssl"] }
log = "0.4"
