[package]
name = "ekiden-storage-base"
version = "0.1.0"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden storage interface traits"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"

[dependencies]
ekiden-common = { path = "../../common", version = "0.1.0" }

[target.'cfg(not(target_env = "sgx"))'.dependencies]
ekiden-storage-api = { path = "../api", version = "0.1.0" }
grpcio = "0.2.2"
