[package]
name = "ekiden-consensus-client"
version = "0.1.0-alpha.4"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden Consensus RPC CLient"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"

[dependencies]
ekiden-common = { path = "../../common", version = "0.1.0-alpha.4" }
ekiden-consensus-api = { path = "../api", version = "0.1.0-alpha.4" }
ekiden-consensus-base = { path = "../base", version = "0.1.0-alpha.4" }
grpcio = "0.2.2"
