[package]
name = "ekiden-consensus-client"
version = "0.2.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden Consensus RPC CLient"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"

[dependencies]
ekiden-common = { path = "../../common", version = "0.2.0-alpha" }
ekiden-di = { path = "../../di", version = "0.2.0-alpha" }
ekiden-consensus-api = { path = "../api", version = "0.2.0-alpha" }
ekiden-consensus-base = { path = "../base", version = "0.2.0-alpha" }
grpcio = { git = "https://github.com/ekiden/grpc-rs", tag = "v0.3.0-ekiden1", features = ["openssl"] }
