[package]
name = "ekiden-consensus-api"
version = "0.1.0-alpha.2"
authors = ["Ekiden Developers <ekiden-dev@googlegroups.com>"]
description = "Ekiden consensus node API"
keywords = ["ekiden"]
repository = "https://github.com/ekiden/ekiden"
build = "build.rs"

[dependencies]
protobuf = "1.4.2"
grpcio = "0.2.2"
futures = "0.1"

[build-dependencies]
ekiden-tools = { path = "../../tools", version = "0.1.0-alpha.2" }
protoc-grpcio = "0.1.0"
