[package]
name = "ekiden-compute-api"
version = "0.2.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden compute node API"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"
build = "build.rs"

[dependencies]
protobuf = "~2.0"
ekiden-grpcio = { version = "0.3.2", features = ["openssl"] }
futures = "0.1"

[build-dependencies]
ekiden-tools = { path = "../../tools", version = "0.2.0-alpha" }
protoc-grpcio = "0.2.0"
