[package]
name = "ekiden-common"
version = "0.1.0-alpha.2"
authors = ["Ekiden Developers <ekiden-dev@googlegroups.com>"]
description = "Ekiden common functionality (available to both trusted and untrusted parts)"
keywords = ["ekiden"]
repository = "https://github.com/ekiden/ekiden"

[features]
default = []
profiling = []

[dependencies]
protobuf = "1.4.3"
byteorder = "1"

[target.'cfg(not(target_env = "sgx"))'.dependencies]
rand = "0.4.2"
