[package]
name = "ekiden-compute"
version = "0.1.0-alpha.2"
authors = ["Ekiden Developers <ekiden-dev@googlegroups.com>"]
description = "Ekiden compute node"
keywords = ["ekiden"]
repository = "https://github.com/ekiden/ekiden"
build = "build.rs"

[features]
no_cache = []
no_diffs = []

[dependencies]
ekiden-core = { path = "../core/common", version = "0.1.0-alpha.2" }
ekiden-untrusted = { path = "../core/untrusted", version = "0.1.0-alpha.2" }
ekiden-rpc-client = { path = "../rpc/client", version = "0.1.0-alpha.2" }
ekiden-compute-api = { path = "./api", version = "0.1.0-alpha.2" }
ekiden-consensus-api = { path = "../consensus/api", version = "0.1.0-alpha.2" }
protobuf = "1.4.2"
grpc = "0.2.1"
futures = "0.1"
futures-cpupool = "0.1.*"
sgx_types = { git = "https://github.com/ekiden/rust-sgx-sdk", tag = "v0.9.7-ekiden1" }
tls-api = "0.1.12"
httpbis = "0.4.1"
thread_local = "0.3.5"
clap = "2.29.1"
reqwest = "0.8.2"
base64 = "0.9.0"
prometheus = "0.3.10"
hyper = "0.11"
time = "0.1"
tokio-core = "0.1"

[build-dependencies]
ekiden-tools = { path = "../tools", version = "0.1.0-alpha.2" }
ekiden-edl = { path = "../core/edl", version = "0.1.0-alpha.2" }
protoc-rust = "1.4"
protoc-rust-grpc = "0.2.1"
