# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "v1.0.2"

[[constraint]]
  name = "github.com/tendermint/iavl"
  source = "https://github.com/oasislabs/iavl"
  version = "=0.11.0-ekiden1"

[[constraint]]
  name = "github.com/tendermint/tendermint"
  source = "https://github.com/oasislabs/tendermint"
  version = "=v0.24.0-ekiden1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "v1.2.2"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "=1.13.0"

[[constraint]]
  name = "golang.org/x/crypto"
  branch = "master"

[[constraint]]
  name = "github.com/hashicorp/golang-lru"
  version = "v0.5.0"

[[override]]
  name = "golang.org/x/net"
  branch = "master"

[[override]]
  name = "git.schwanenlied.me/yawning/bsaes.git"
  source = "https://github.com/yawning/bsaes"

[prune]
  go-tests = true
  unused-packages = true

[[override]]
  name = "github.com/tendermint/go-amino"
  version = "=v0.10.1"

[[override]]
    name = "github.com/spf13/viper"
    version = "=v1.0.2"

[[override]]
    name = "github.com/spf13/cobra"
    version = "=v0.0.3"

[[override]]
  name = "github.com/tendermint/iavl"
  version = "=0.11.0-ekiden1"

[[override]]
  name = "github.com/tendermint/tendermint"
  version = "=v0.24.0-ekiden1"

[[override]]
  name = "github.com/prometheus/client_golang"
  revision = "ae27198cdd90bf12cd134ad79d1366a6cf49f632"

# https://github.com/tendermint/tendermint/issues/1777
[[override]]
  name = "google.golang.org/genproto"
  revision = "7fd901a49ba6a7f87732eb344f6e3c5b19d1b200"
