############################################
# Single node configuration for development.
############################################
#
# NOTE: This sets up a single node that is a Tendermint validator,
#       a storage node and an Ekiden worker at the same time. In
#       actual deployments these nodes will likely run separately.
#
datadir: /tmp/ekiden-single-node

# Debug.
#
# Enable test keys, and the built in test entity to reduce config maintenance
# burden.
debug:
  allow_test_keys: true
  test_entity: true

# Logging.
# Per-module log levels are defined below. If you prefer just one unified log level, you can use:
# log:
#   level: debug
log:
  level:
    # Per-module log levels. Longest prefix match will be taken. Fallback to "default", if no match.
    default: debug
    tendermint: warn
    tendermint/context: error

# Genesis.
genesis:
  file: /tmp/ekiden-single-node/genesis.json

# Internal gRPC services.
grpc:
  log:
    verbose_debug: true

# Worker configuration.
worker:
  compute:
    enabled: true
  runtime:
    backend: sandboxed
    loader: target/debug/ekiden-runtime-loader
    id: "0000000000000000000000000000000000000000000000000000000000000000"
    binary: target/debug/simple-keyvalue
  storage:
    enabled: true
  txnscheduler:
    enabled: true
  merge:
    enabled: true
  client:
    port: 9200
    addresses:
      - "127.0.0.1:9200"
  p2p:
    port: 9100
  keymanager:
    enabled: true
    may_generate: true
    runtime:
      id: "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"
      binary: target/debug/ekiden-keymanager-runtime
      loader: target/debug/ekiden-runtime-loader

# Consensus backend.
consensus:
  backend: tendermint
  validator: true

# Epochtime backend.
epochtime:
  backend: tendermint
  tendermint:
    # This makes each epoch last for 30 tendermint blocks.
    interval: 30

# Storage backend.
storage:
  backend: leveldb

# Roothash backend.
roothash:
  tendermint:
    index_blocks: true

# Tendermint backend configuration.
tendermint:
  consensus:
    timeout_commit: 1s

# Client configuration.
client:
  indexer:
    runtimes:
      - "0000000000000000000000000000000000000000000000000000000000000000"

# Scheduler configuration.
scheduler:
  debug:
    static_validators: true

# Tracing settings.
#tracing:
#  enabled: 1
#  reporter:
#    agent_addr: jaeger:6831
#  sampler:
#    # Sampling frequency, 100% by default.
#    param: 1.0
