[package]
name = "ekiden-trusted"
version = "0.1.0-alpha.4"
authors = ["Ekiden Developers <ekiden-dev@googlegroups.com>"]
description = "Ekiden trusted library"
keywords = ["ekiden"]
repository = "https://github.com/ekiden/ekiden"

[dependencies]
cargo-cult = "0.1.0"
ekiden-enclave-trusted = { path = "../../enclave/trusted", version = "0.1.0-alpha.4" }
ekiden-rpc-trusted = { path = "../../rpc/trusted", version = "0.1.0-alpha.4" }
ekiden-db-trusted = { path = "../../db/trusted", version = "0.1.0-alpha.4" }
ekiden-contract-trusted = { path = "../../contract/trusted", version = "0.1.0-alpha.4" }
ekiden-key-manager-client = { path = "../../contracts/key-manager/client", version = "0.1.0-alpha.4" }
