[package]
name = "ekiden-enclave-untrusted"
version = "0.2.0-alpha"
authors = [
    "Raymond Cheng <me@raymondcheng.net>",
    "Jernej Kos <jernej@kos.mx>"
]

[features]
sgx-simulation = []

[dependencies]
base64 = "0.9.0"
reqwest = "0.8.2"
protobuf = "~2.0"
sgx_types = { git = "https://github.com/oasislabs/rust-sgx-sdk", tag = "v1.0.1-ekiden3" }
sgx_urts = { git = "https://github.com/oasislabs/rust-sgx-sdk", tag = "v1.0.1-ekiden3", features = ["global_init"] }
ekiden-common = { path = "../../common", version = "0.2.0-alpha" }
ekiden-core = { path = "../../core/common", version = "0.2.0-alpha" }
ekiden-enclave-common = { path = "../common", version = "0.2.0-alpha" }
log = "0.4"
serde = "1.0.71"
serde_cbor = { git = "https://github.com/oasislabs/cbor", tag = "v0.9.0-ekiden1" }

[build-dependencies]
ekiden-tools = { path = "../../tools", version = "0.2.0-alpha" }
