[package]
name = "ekiden-enclave-untrusted"
version = "0.1.0-alpha.3"
authors = [
    "Raymond Cheng <me@raymondcheng.net>",
    "Jernej Kos <jernej@kos.mx>"
]

[features]
sgx-simulation = []

[dependencies]
protobuf = "1.4.3"
sgx_types = { git = "https://github.com/ekiden/rust-sgx-sdk", tag = "v0.9.7-ekiden2" }
sgx_urts = { git = "https://github.com/ekiden/rust-sgx-sdk", tag = "v0.9.7-ekiden2" }
ekiden-common = { path = "../../common", version = "0.1.0-alpha.3" }
ekiden-enclave-common = { path = "../common", version = "0.1.0-alpha.3" }

[build-dependencies]
ekiden-tools = { path = "../../tools", version = "0.1.0-alpha.3" }
