[package]
name = "ekiden-rpc-untrusted"
version = "0.2.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden RPC (untrusted part)"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"

[features]
sgx-simulation = []

[dependencies]
sgx_types = { git = "https://github.com/oasislabs/rust-sgx-sdk", tag = "v1.0.1-ekiden3" }
sgx_urts = { git = "https://github.com/oasislabs/rust-sgx-sdk", tag = "v1.0.1-ekiden3" }
protobuf = "~2.0"
lazy_static = "1.0"
ekiden-common = { path = "../../common", version = "0.2.0-alpha" }
ekiden-enclave-untrusted = { path = "../../enclave/untrusted", version = "0.2.0-alpha" }
ekiden-rpc-common = { path = "../common", version = "0.2.0-alpha" }
serde = "1.0.71"
serde_cbor = "0.8.2"

[build-dependencies]
ekiden-tools = { path = "../../tools", version = "0.2.0-alpha" }
