[package]
name = "ekiden-untrusted"
version = "0.1.0"
authors = ["Ekiden Developers <ekiden-dev@googlegroups.com>"]
description = "Ekiden untrusted library"
keywords = ["ekiden"]
repository = "https://github.com/ekiden/ekiden"

[dependencies]
ekiden-enclave-untrusted = { path = "../../enclave/untrusted", version = "0.1.0" }
ekiden-rpc-untrusted = { path = "../../rpc/untrusted", version = "0.1.0" }
ekiden-db-untrusted = { path = "../../db/untrusted", version = "0.1.0" }
ekiden-contract-untrusted = { path = "../../contract/untrusted", version = "0.1.0" }

[build-dependencies]
ekiden-tools = { path = "../../tools", version = "0.1.0" }
