[package]
name = "ekiden-common-api"
version = "0.2.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden common API"
keywords = ["ekiden"]
repository = "https://github.com/ekiden/ekiden"
build = "build.rs"

[dependencies]
protobuf = "~2.0"

[target.'cfg(not(target_env = "sgx"))'.dependencies]
ekiden-grpcio = { version = "0.3.2", features = ["openssl"] }
futures = "0.1"

[build-dependencies]
ekiden-tools = { path = "../../tools", version = "0.2.0-alpha" }

[target.'cfg(not(target_env = "sgx"))'.build-dependencies]
protoc-grpcio = "0.2.0"
