[package]
name = "ekiden-contract-common"
version = "0.2.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden common contract functionality"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"

[dependencies]
ekiden-common = { path = "../../common", version = "0.2.0-alpha" }
serde = "=1.0.59"
serde_derive = "1.0"
serde_cbor = "0.8.2"
