[package]
name = "oasis-core-tools"
version = "0.3.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
serde_derive = "1.0"
serde = "1.0.71"
toml = "0.5.0"
clap = "2.29.1"
ansi_term = "0.11.0"

[[bin]]
name = "cargo-elf2sgxs"
path ="bin/cargo-elf2sgxs.rs"
