[package]
name = "ekiden-tools"
version = "0.2.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden build tools"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"
build = "build.rs"

[dependencies]
mktemp = "0.3.1"
cc = "1.0"
protoc = "~2.0"
protoc-rust = "~2.0"
protobuf = "~2.0"
sgx_edl = { git = "https://github.com/ekiden/rust-sgx-sdk", tag = "v0.9.8-ekiden1" }
clap = "2.29.1"
ansi_term = "0.11"
toml = "0.4"
serde = "=1.0.59"
serde_derive = "1.0"
error-chain = "0.11.0"
filebuffer = "0.3"
regex = "=1.0.0"
rustc-hex = "1.0.0"

[[bin]]
name = "cargo-ekiden"
path ="bin/main.rs"
