[package]
name = "ekiden-scheduler-base"
version = "0.1.0-alpha.4"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden scheduler interface traits"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"

[dependencies]
ekiden-common = { path = "../../common", version = "0.1.0-alpha.4" }
ekiden-scheduler-api = { path = "../api", version = "0.1.0-alpha.4" }
serde = "1.0"
serde_derive = "1.0"
