[package]
name = "ekiden-scheduler-base"
version = "0.2.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden scheduler interface traits"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"

[dependencies]
ekiden-common = { path = "../../common", version = "0.2.0-alpha" }
ekiden-scheduler-api = { path = "../api", version = "0.2.0-alpha" }
grpcio = { version = "~0.4.2", features = ["openssl"] }
protobuf = "~2.0"
serde = "1.0.71"
serde_derive = "1.0"
