[package]
name = "ekiden-key-manager-client"
version = "0.1.0-alpha.3"
authors = ["Ekiden Developers <ekiden-dev@googlegroups.com>"]
description = "Ekiden key manager client"
keywords = ["ekiden"]
repository = "https://github.com/ekiden/ekiden"

[dependencies]
ekiden-common = { path = "../../../common", version = "0.1.0-alpha.3" }
ekiden-enclave-common = { path = "../../../enclave/common", version = "0.1.0-alpha.3" }
ekiden-rpc-client = { path = "../../../rpc/client", version = "0.1.0-alpha.3" }
ekiden-rpc-common = { path = "../../../rpc/common", version = "0.1.0-alpha.3" }
ekiden-rpc-trusted = { path = "../../../rpc/trusted", version = "0.1.0-alpha.3" }
ekiden-key-manager-api = { path = "../api", version = "0.1.0-alpha.3" }
lazy_static = { version = "1.0", features = ["spin_no_std"] }
