[package]
name = "ekiden-enclave-trusted"
version = "0.2.0-alpha"
authors = [
    "Jernej Kos <jernej@kos.mx>"
]

[dependencies]
ekiden-common = { path = "../../common", version = "0.2.0-alpha" }
ekiden-enclave-common = { path = "../common", version = "0.2.0-alpha" }
lazy_static = { version = "1.0", features = ["spin_no_std"] }
protobuf = "~1.4"
sodalite = "0.3.0"
serde = "=1.0.59"
serde_cbor = "0.8.2"

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { git = "https://github.com/ekiden/rust-sgx-sdk", tag = "v0.9.8-ekiden1" }
