[package]
name = "ekiden-enclave-trusted"
version = "0.2.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]

[dependencies]
ekiden-common = { path = "../../common", version = "0.2.0-alpha" }
ekiden-enclave-common = { path = "../common", version = "0.2.0-alpha" }
lazy_static = { version = "1.1.0", features = ["spin_no_std"] }
log = { version = "0.4", features = ["serde"] }
protobuf = "~2.0"
sodalite = "0.3.0"
serde = "1.0.71"
serde_cbor = { git = "https://github.com/oasislabs/cbor", tag = "v0.9.0-ekiden1" }

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { git = "https://github.com/oasislabs/rust-sgx-sdk", tag = "v1.0.1-ekiden3" }
