[package]
name = "ekiden-registry-dummy"
version = "0.1.0-alpha.4"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden dummy iregistry backend"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"

[dependencies]
ekiden-common = { path = "../../common", version = "0.1.0-alpha.4" }
ekiden-registry-base = { path = "../base", version = "0.1.0-alpha.4" }
serde = "1.0"
serde_cbor = "0.8.2"
